program the_name_of_the_program

    script {
      int main_one = 9
      int main_two
      str string_one = ""
      str string_two = " "
      str string_three = "hi"
      str str_four
      bool bool_one = True
      bool bool_two = False
      bool bool_three
      double doub_one = 2.2
      double doub_two
      # main_one = 11 + 22
    }

    # TODO: duplicates en memoria constante! (False, y default intiial values)   bool bool_two = False y  bool bool_three
