program the_name_of_the_program

    script {
      # int main_one = 3
      # int main_two
      # str string_one = ""
      # str string_two = " "
      # str string_three = "hi"
      # str str_four
      # bool bool_one = True
      # bool bool_two = False
      # bool bool_three
      # double doub_one = 2.2
      # double doub_two
      # main_one = 11 + 22
      # main_one = 20 - 3
      # main_one = 2 * 10
      # main_one = 20 / 4
      # main_one = main_one / main_one

      # bool_three = 1 > 2
      # bool_three = 3 <= 3
      # bool_three = 1 is 2



      # eval("hello world")
      # eval(doub_one)

    }

    h1{<^ "hello" ^>}

    # TODO: duplicates en memoria constante! (False, y default intiial values)   bool bool_two = False y  bool bool_three
