program the_name_of_the_program
    script {

      int global_int_1000
      int global_int_1001
      double global_int_2000
      double global_int_2001
      bool global_bool_3000
      bool global_bool_3001
      str global_str_4000
      str global_str_4001

      def my_function2 () {
        int local_int_5000
        bool local_bool_7000
        str local_str_8000
      }

      def my_function3 () {
        int local_int_5000
        bool local_bool_7000
        str local_str_8000
      }
    }
