# Don't move, otherwise the TEST will break

program the_name_of_the_program
    script {
        # str my_slice [2] = ["a","b"]
        # int another_slice [1] = [0]
        int CCC

        # int ARRAY [1] = [0]
        # int BBB
        int another_slice [3] = [1,2,3]
        # int another_slice [1][1]
        # int slice2D [1][1] = [[1]]
        # int another_2D_slice [2][2] = [[1,3],[1,2]]
        # int slice [3][3] = [[1,2,3],[1,2,3],[1,2,3]]
        # int elda [6][7] = [[1]]
        int BBC

    }
#
