program the_name_of_the_program

    script {
      int main_one = 1
      int main_two = 2
      int main_three
      int main_four

      main_three = main_one + main_two
      main_four = main_two * main_two

      main_four = main_two * main_two

      def func1() {
        int func1_one = 1
        int func1_two = 2
        int func1_three
        int func1_four

        func1_three = func1_one + func1_two
        func1_four = func1_two * func1_two

        func1_four = func1_two * func1_two

      }



    }
