program the_name_of_the_program
    script {}

    div class : "container" {
      ul class : "collection" {
        li class : "collection-item teal lighten-2" {
            <^ "Ana Karen" ^>
        }
        li class : "collection-item teal lighten-2" {
            <^ "Sergio" ^>
        }
        li class : "collection-item teal lighten-2" {
            <^ "Hernan" ^>
        }
      }
      ol class : "collection" {
        li class : "collection-item teal lighten-2" {
          <^ "Ana Karen" ^>
        }
        li class : "collection-item teal lighten-2" {
          <^ "Sergio" ^>
        }
        li class : "collection-item teal lighten-2" {
          <^ "Hernan" ^>
        }
      }
    }
